permalink:           pretty

# Setup
title:               Serendipity Styx Edition
tagline:             'Styx is what Serendipity should be'
description:         ''
url:                 https://ophian.github.io
paginate:            5
paginate_path:       "/blog/page:num/"
highlighter:         rouge

# About/contact
author:
  name:              Ian Styx
  url:               https://github.com/ophian/styx
  email:             just no - get me over github please

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
