permalink:           pretty

# Setup
title:               Serendipity Styx Edition
tagline:             'Styx is what Serendipity should be'
description:         ''
url:                 https://ophian.github.io
paginate:            5
highlighter:         pygments

# About/contact
author:
  name:              Ian
  url:               https://github.com/ophian/styx
  email:             just no - get me over github please

gems:
  - jekyll-sitemap
